[package]
name = "mdsplit"
version = "0.1.0"
authors = ["Sagi Schwarz <mail@sagischwarz.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "^1.4"
chrono = "^0.4"
structopt = "^0.3"